"""话题历史工具常量。"""

DEFAULT_DEDUPLICATION_DAYS = 30
TOPIC_HISTORY_SCHEMA_VERSION = 1
ACTIVE_TOPIC_STATUSES = ["reserved", "completed", "published"]
SUPPORTED_TOPIC_STATUSES = [*ACTIVE_TOPIC_STATUSES, "failed"]
