"""Cloudflare 数据服务常量。"""

CLOUDFLARE_DATA_API_URL_ENV = "CLOUDFLARE_DATA_API_URL"
CLOUDFLARE_DATA_API_TOKEN_ENV = "CLOUDFLARE_DATA_API_TOKEN"
DEFAULT_REQUEST_TIMEOUT_SECONDS = 30
MAX_RESPONSE_BYTES = 4 * 1024 * 1024

