"""Facebook / Instagram Reels 发布常量。"""

META_GRAPH_VERSION = "v21.0"
FACEBOOK_GRAPH_BASE = f"https://graph.facebook.com/{META_GRAPH_VERSION}"
INSTAGRAM_GRAPH_BASE = f"https://graph.instagram.com/{META_GRAPH_VERSION}"
META_REQUEST_TIMEOUT_SECONDS = 60
META_UPLOAD_TIMEOUT_SECONDS = 600
INSTAGRAM_CONTAINER_POLL_SECONDS = 5
INSTAGRAM_CONTAINER_TIMEOUT_SECONDS = 600
META_PLATFORMS = ("facebook", "instagram")
