"""人生文案文生图业务线配置。"""

from ._constants import (
    ARTICLE_PROMPT_PATH,
    BGM_FADE_IN_SECONDS,
    BGM_FADE_OUT_SECONDS,
    BGM_GAIN,
    BGM_ID,
    COVER_FRAME_SECONDS,
    EXAMPLES_DIR,
    HOOKS_PATH,
    INTRO,
    MATRIXMEDIA_ACCOUNT_GROUP,
    MIX_GAIN,
    PAGE_FLIP_SFX_PATH,
    REFERENCE_IMAGE_PATH,
    SHOT_IMAGE_RULES_PATH,
    TOPIC_DEDUPLICATION_DAYS,
    TTS_RATE,
    TTS_TRIM_TRAILING_SILENCE,
    TTS_VOICE,
    VIDEO_RADIO,
    VIDEO_SIZE,
    VISUAL_STYLE,
    WORKFLOW_ID,
)


def get_line() -> dict:
    return {
        "id": WORKFLOW_ID,
        "visual_style": VISUAL_STYLE,
        "video_size": VIDEO_SIZE,
        "video_radio": VIDEO_RADIO,
        "bgm_id": BGM_ID,
        "bgm_gain": BGM_GAIN,
        "mix_gain": MIX_GAIN,
        "bgm_fade_in": BGM_FADE_IN_SECONDS,
        "bgm_fade_out": BGM_FADE_OUT_SECONDS,
        "tts_voice": TTS_VOICE,
        "tts_rate": TTS_RATE,
        "tts_trim_trailing_silence": TTS_TRIM_TRAILING_SILENCE,
        "cover_frame_seconds": COVER_FRAME_SECONDS,
        "topic_deduplication_days": TOPIC_DEDUPLICATION_DAYS,
        "matrixmedia_account_group": MATRIXMEDIA_ACCOUNT_GROUP,
        "article_prompt_path": ARTICLE_PROMPT_PATH,
        "examples_dir": EXAMPLES_DIR,
        "hooks_path": HOOKS_PATH,
        "shot_image_rules_path": SHOT_IMAGE_RULES_PATH,
        "extra_reference_image_path": REFERENCE_IMAGE_PATH,
        "intro": INTRO,
        "intro_sfx_path": PAGE_FLIP_SFX_PATH,
    }
