"""从图片生成镜头的编码参数。

镜头只出画面、无音轨；成片再一次叠配音/BGM/字幕。编码参数须与 generate_final_video 一致。
"""

from __future__ import annotations

from pathlib import Path

SHOT_RENDERER_VERSION = 19
SHOT_FPS = 30
SHOT_CODEC = "libx264"
SHOT_PRESET = "veryfast"
SHOT_CRF = 21
SHOT_TUNE_STILLIMAGE = "stillimage"
SHOT_PIXEL_FORMAT = "yuv420p"
SHOT_AUDIO_CODEC = "aac"
SHOT_AUDIO_RATE = 48_000
SHOT_AUDIO_CHANNELS = 2
# zoompan 在成品分辨率上会把缓慢平移取整到整像素。
# 先放到 2 倍画布上算运镜，再缩回成品尺寸，减轻抖动。
SHOT_MOTION_INPUT_SCALE = 2
SHOT_MOTION_WORK_SCALE = 2
SHOT_RENDER_MIN_TIMEOUT_SECONDS = 360
SHOT_RENDER_TIMEOUT_PER_SECOND = 15
# 循环静图必须有限时长，否则 -shortest 停不住，每个镜头会编满超时时间。
SHOT_IMAGE_LOOP_PAD_SECONDS = 0.25
SHOT_PROBE_TIMEOUT_SECONDS = 30

# 片头（generate_shot_from_intro）固定 1920x1080
INTRO_RENDERER_VERSION = 21
INTRO_STYLES = ("slide_in_shutter", "page_flip")
OUTPUT_WIDTH = 1920
OUTPUT_HEIGHT = 1080
OUTPUT_SIZE = f"{OUTPUT_WIDTH}:{OUTPUT_HEIGHT}"
CANVAS_SIZE = f"{OUTPUT_WIDTH}x{OUTPUT_HEIGHT}"
RESOLUTION = CANVAS_SIZE
FPS = SHOT_FPS
INTRO_RENDER_MIN_TIMEOUT_SECONDS = 180
INTRO_RENDER_TIMEOUT_PER_SECOND = 30

FIRST_SLIDE_SECONDS = 0.675
SECOND_SLIDE_START_SECONDS = 0.0
SLIDE_IN_SECONDS = 0.675
HOLD_SECONDS = 0.5
CARD_SCALE = 2 / 3
SHUTTER_START_SECONDS = SLIDE_IN_SECONDS + HOLD_SECONDS
FLASH_SECONDS = 0.18
PHOTO_EXPAND_SECONDS = 0.5
TOTAL_SECONDS = SHUTTER_START_SECONDS + FLASH_SECONDS + PHOTO_EXPAND_SECONDS
CARD_SHADOW_MARGIN = 96
CARD_SHADOW_OFFSET_X = 24
CARD_SHADOW_OFFSET_Y = 36
CARD_SHADOW_OPACITY = 0.52
CARD_SHADOW_BLUR = 40

_STATIC_DIR = Path(__file__).resolve().parent / "static"
SFX_ALERT_PATH = _STATIC_DIR / "alert.wav"
SFX_SHUTTER_PATH = _STATIC_DIR / "shutter.wav"
SFX_ALERT_SECONDS = SLIDE_IN_SECONDS
SFX_ALERT_GAIN = 1.35
SFX_SHUTTER_SECONDS = 0.456
SFX_SHUTTER_GAIN = 1.8

PAGE_FLIP_COUNT = 9
PAGE_FLIP_SECONDS = 0.18
PAGE_FLIP_MIN_HOLD_SECONDS = 0.05
PAGE_FLIP_MIN_ZOOM_SECONDS = 0.6
PAGE_FLIP_ZOOM_TO = 1.18
PAGE_FLIP_SFX_GAIN = 1.15
