"""语音转文字常量。"""

GROQ_ASR_MODEL = "whisper-large-v3"
GROQ_ASR_BASE_URL = "https://api.groq.com/openai/v1"
GROQ_ASR_CHUNK_SECONDS = 1200
GROQ_CONNECT_TIMEOUT_SECONDS = 30
GROQ_READ_TIMEOUT_SECONDS = 1800
AUDIO_SAMPLE_RATE = 16_000
AUDIO_BITRATE = "64k"
SUPPORTED_LANGUAGES = ("zh", "en")
