"""千问文本生成常量。"""

from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
CONFIG_PATH = PROJECT_ROOT / "config" / "text_generation.json"
DASHSCOPE_API_KEY_ENV = "DASHSCOPE_API_KEY"
DASHSCOPE_BASE_URL_ENV = "DASHSCOPE_BASE_URL"
DASHSCOPE_MODEL_ENV = "DASHSCOPE_MODEL"
DASHSCOPE_ENABLE_THINKING_ENV = "DASHSCOPE_ENABLE_THINKING"
DEFAULT_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
DEFAULT_MODEL = "qwen3.8-max"
DEFAULT_TIMEOUT_SECONDS = 180
DEFAULT_TEMPERATURE = 0.7
MAX_RESPONSE_BYTES = 8 * 1024 * 1024

