"""千问文本生成常量。"""

DASHSCOPE_API_KEY_ENV = "DASHSCOPE_API_KEY"
DASHSCOPE_API_KEY_FINANCE_ENV = "DASHSCOPE_API_KEY_FINANCE"
DASHSCOPE_API_KEY_LANGUAGE_ENV = "DASHSCOPE_API_KEY_LANGUAGE"
DASHSCOPE_BUSINESS_LINE_ENV = "DASHSCOPE_BUSINESS_LINE"
DASHSCOPE_API_KEY_BY_LINE = {
    "finance": DASHSCOPE_API_KEY_FINANCE_ENV,
    "language_learning": DASHSCOPE_API_KEY_LANGUAGE_ENV,
}
DASHSCOPE_BASE_URL_ENV = "DASHSCOPE_BASE_URL"
DASHSCOPE_MODEL_ENV = "DASHSCOPE_MODEL"
DASHSCOPE_VISION_MODEL_ENV = "DASHSCOPE_VISION_MODEL"
DASHSCOPE_ENABLE_THINKING_ENV = "DASHSCOPE_ENABLE_THINKING"
DEFAULT_BASE_URL = "https://dashscope.aliyuncs.com/compatible-mode/v1"
DEFAULT_MODEL = "qwen3.8-max"
DEFAULT_TIMEOUT_SECONDS = 180
DEFAULT_TEMPERATURE = 0.7
MAX_RESPONSE_BYTES = 8 * 1024 * 1024
